spring:
  profiles:
    active:
    - dev  #开发环境

#  redis:
#    database: 0
#    host: localhost
#    port: 6379
#    password: 
#    pool:
#      max-active: 8
#      max-wait: -1
#      max-idle: 8
#      min-idle: 0
#    timeout: 3000

#mybatis
mybatis:
  mapper-locations:
  - classpath:mapper/*/*.xml
  configuration:
    mapUnderscoreToCamelCase: true   #自动驼峰转换
    useColumnLabel: true
  
lichi:
#验证码配置
  code:
    image:
      height: 23
      width: 67
    sms:
      expire-in: 60
      url: 
      length: 6
      
#oauth2.0安全认证的参数
  oauth2-properties:
    clients:
    - client-id: lichi
      client-secret: 123456
      access-token-validity-seconds: 7200
      grant-types:
      - password, refresh_token,implicit
      scopes:
      - all, read, write
    jwt-signing-key: lichi
    storeType: jwt   #token的存放方式
    
