spring:
  profiles:
    active:
    - dev
  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Chongqing
#    default-property-inclusion: non-null
  redis:
    database: 0
    host: 192.168.100.109
#    host: localhost
    port: 6379
    password: 
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 3000
  http:
    multipart:
      enabled: true
      file-size-threshold: 0
      location: 
      max-file-size: 1MB
      max-request-size: 10Mb
mybatis:
  mapper-locations:
  - classpath:mapper/*/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
    useColumnLabel: true
mapper:
  mappers:
  - com.lichi.increaselimit.common.mapper.BaseMapper
  not-empty: false
  identity: MYSQL
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
lichi:
  code:
    image:
      height: 23
      width: 67
    sms:
      expire-in: 900
      url: 
      length: 6
      
logging:
  config: 
  - classpath:logback-lichi.xml